---
## PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cce-evs-nexus3
  namespace: nexus
  annotations:
    everest.io/disk-volume-type: SAS
  labels:
    failure-domain.beta.kubernetes.io/region: cn-east-3
    failure-domain.beta.kubernetes.io/zone: cn-east-3a
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: csi-disk
---
