apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  pvc-sfs-maven-cache
  namespace: cicd
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-storage
